<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->delete();

        DB::table('cities')->insert(
            [
                0   =>
                    [
                        'name'         => 'Riga',
                        'country_code' => 'LVA',
                        'population'   => 742572,
                        'capital'      => true,
                        'area_size'    => '307.17',
                        'lat'          => '56.95',
                        'lng'          => '24.1',
                        'county_id'    => 1,
                        'region_id'    => 5,
                        'type'         => 'city',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                1   =>
                    [
                        'name'         => 'Daugavpils',
                        'country_code' => 'LVA',
                        'population'   => 111564,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '55.883333',
                        'lng'          => '26.533333',
                        'county_id'    => 2,
                        'region_id'    => 4,
                        'type'         => 'city',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                2   =>
                    [
                        'name'         => 'Liepāja',
                        'country_code' => 'LVA',
                        'population'   => 85132,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.516667',
                        'lng'          => '21.016667',
                        'county_id'    => 3,
                        'region_id'    => 3,
                        'type'         => 'city',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                3   =>
                    [
                        'name'         => 'Jelgava',
                        'country_code' => 'LVA',
                        'population'   => 67207,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.65',
                        'lng'          => '23.712778',
                        'county_id'    => 4,
                        'region_id'    => 1,
                        'type'         => 'city',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                4   =>
                    [
                        'name'         => 'Ventspils',
                        'country_code' => 'LVA',
                        'population'   => 42884,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.389881',
                        'lng'          => '21.572878',
                        'county_id'    => 5,
                        'region_id'    => 3,
                        'type'         => 'city',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                5   =>
                    [
                        'name'         => 'Rēzekne',
                        'country_code' => 'LVA',
                        'population'   => 38340,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.5',
                        'lng'          => '27.316667',
                        'county_id'    => 6,
                        'region_id'    => 4,
                        'type'         => 'city',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                6   =>
                    [
                        'name'         => 'Inčukalns',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.098056',
                        'lng'          => '24.686389',
                        'county_id'    => 7,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                7   =>
                    [
                        'name'         => 'Ķekava',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.829444',
                        'lng'          => '24.237222',
                        'county_id'    => 8,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                8   =>
                    [
                        'name'         => 'Valka',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.766667',
                        'lng'          => '26.0',
                        'county_id'    => 9,
                        'region_id'    => 2,
                        'type'         => 'city',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                9   =>
                    [
                        'name'         => 'Loja',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.154444',
                        'lng'          => '24.644444',
                        'county_id'    => 10,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                10  =>
                    [
                        'name'         => 'Mārupe',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.903209',
                        'lng'          => '24.046678',
                        'county_id'    => 11,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                11  =>
                    [
                        'name'         => 'Drabeši',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.233333',
                        'lng'          => '25.283333',
                        'county_id'    => 12,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                12  =>
                    [
                        'name'         => 'Iecava',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.598611',
                        'lng'          => '24.202222',
                        'county_id'    => 13,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                13  =>
                    [
                        'name'         => 'Salacgrīva',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.753611',
                        'lng'          => '24.358056',
                        'county_id'    => 14,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                14  =>
                    [
                        'name'         => 'Ķegums',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.744167',
                        'lng'          => '24.715833',
                        'county_id'    => 15,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                15  =>
                    [
                        'name'         => 'Sigulda',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.151944',
                        'lng'          => '24.864722',
                        'county_id'    => 16,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                16  =>
                    [
                        'name'         => 'Jaunpils',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.7325',
                        'lng'          => '23.013611',
                        'county_id'    => 17,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                17  =>
                    [
                        'name'         => 'Alsunga',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.980106',
                        'lng'          => '21.564009',
                        'county_id'    => 18,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                18  =>
                    [
                        'name'         => 'Tērvete',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.478056',
                        'lng'          => '23.386667',
                        'county_id'    => 19,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                19  =>
                    [
                        'name'         => 'Talsi',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.246509',
                        'lng'          => '22.587578',
                        'county_id'    => 20,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                20  =>
                    [
                        'name'         => 'Cesvaine',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.966667',
                        'lng'          => '26.316667',
                        'county_id'    => 21,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                21  =>
                    [
                        'name'         => 'Cēsis',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.3',
                        'lng'          => '25.25',
                        'county_id'    => 22,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                22  =>
                    [
                        'name'         => 'Kocēni',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.516667',
                        'lng'          => '25.333333',
                        'county_id'    => 23,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                23  =>
                    [
                        'name'         => 'Koknese',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.65',
                        'lng'          => '25.433333',
                        'county_id'    => 24,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                24  =>
                    [
                        'name'         => 'Dundaga',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.50498',
                        'lng'          => '22.350408',
                        'county_id'    => 25,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                25  =>
                    [
                        'name'         => 'Priekuļi',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.316667',
                        'lng'          => '25.366667',
                        'county_id'    => 26,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                26  =>
                    [
                        'name'         => 'Roja',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.501463',
                        'lng'          => '22.808806',
                        'county_id'    => 27,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                27  =>
                    [
                        'name'         => 'Rauna',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.333333',
                        'lng'          => '25.616667',
                        'county_id'    => 28,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                28  =>
                    [
                        'name'         => 'Aloja',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.766944',
                        'lng'          => '24.8825',
                        'county_id'    => 29,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                29  =>
                    [
                        'name'         => 'Rucava',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.166667',
                        'lng'          => '21.15',
                        'county_id'    => 30,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                30  =>
                    [
                        'name'         => 'Lielvārde',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.7225',
                        'lng'          => '24.805',
                        'county_id'    => 31,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                31  =>
                    [
                        'name'         => 'Murmuiža',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.483333',
                        'lng'          => '25.483333',
                        'county_id'    => 32,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                32  =>
                    [
                        'name'         => 'Vecvārkava',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.19838',
                        'lng'          => '26.508107',
                        'county_id'    => 33,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                33  =>
                    [
                        'name'         => 'Bauska',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.407945',
                        'lng'          => '24.194428',
                        'county_id'    => 34,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                34  =>
                    [
                        'name'         => 'Ērgļi',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.9',
                        'lng'          => '25.633333',
                        'county_id'    => 35,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                35  =>
                    [
                        'name'         => 'Varakļāni',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.616667',
                        'lng'          => '26.733333',
                        'county_id'    => 36,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                36  =>
                    [
                        'name'         => 'Ulbroka',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.936297',
                        'lng'          => '24.303873',
                        'county_id'    => 37,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                37  =>
                    [
                        'name'         => 'Mazsalaca',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.866667',
                        'lng'          => '25.05',
                        'county_id'    => 38,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                38  =>
                    [
                        'name'         => 'Lubāna',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.9',
                        'lng'          => '26.716667',
                        'county_id'    => 39,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                39  =>
                    [
                        'name'         => 'Ikšķile',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.833333',
                        'lng'          => '24.5',
                        'county_id'    => 40,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                40  =>
                    [
                        'name'         => 'Ragana',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.181667',
                        'lng'          => '24.714444',
                        'county_id'    => 41,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                41  =>
                    [
                        'name'         => 'Jaunjelgava',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.613187',
                        'lng'          => '25.083161',
                        'county_id'    => 42,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                42  =>
                    [
                        'name'         => 'Ludza',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.539584',
                        'lng'          => '27.718911',
                        'county_id'    => 43,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                43  =>
                    [
                        'name'         => 'Viļāni',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.55',
                        'lng'          => '26.95',
                        'county_id'    => 44,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                44  =>
                    [
                        'name'         => 'Grobiņa',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.55',
                        'lng'          => '21.166667',
                        'county_id'    => 45,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                45  =>
                    [
                        'name'         => 'Rūjiena',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.9',
                        'lng'          => '25.316667',
                        'county_id'    => 46,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                46  =>
                    [
                        'name'         => 'Alūksne',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.421622',
                        'lng'          => '27.046622',
                        'county_id'    => 47,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                47  =>
                    [
                        'name'         => 'Aglona',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.133333',
                        'lng'          => '27.016667',
                        'county_id'    => 48,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                48  =>
                    [
                        'name'         => 'Burtnieki',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.7',
                        'lng'          => '25.266667',
                        'county_id'    => 49,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                49  =>
                    [
                        'name'         => 'Pāvilosta',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.889772',
                        'lng'          => '21.181737',
                        'county_id'    => 50,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                50  =>
                    [
                        'name'         => 'Kārsava',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.787369',
                        'lng'          => '27.673208',
                        'county_id'    => 51,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                51  =>
                    [
                        'name'         => 'Jūrmala',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.956685',
                        'lng'          => '23.723328',
                        'county_id'    => 52,
                        'region_id'    => 5,
                        'type'         => 'city',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                52  =>
                    [
                        'name'         => 'Dagda',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.096133',
                        'lng'          => '27.532773',
                        'county_id'    => 53,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                53  =>
                    [
                        'name'         => 'Stalbe',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.366667',
                        'lng'          => '25.05',
                        'county_id'    => 54,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                54  =>
                    [
                        'name'         => 'Smārde',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.953326',
                        'lng'          => '23.33865',
                        'county_id'    => 55,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                55  =>
                    [
                        'name'         => 'Mērsrags',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.336412',
                        'lng'          => '23.123466',
                        'county_id'    => 56,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                56  =>
                    [
                        'name'         => 'Līvāni',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.366667',
                        'lng'          => '26.183333',
                        'county_id'    => 57,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                57  =>
                    [
                        'name'         => 'Vecpiebalga',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.016667',
                        'lng'          => '25.833333',
                        'county_id'    => 58,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                58  =>
                    [
                        'name'         => 'Jaunpiebalga',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.183333',
                        'lng'          => '26.05',
                        'county_id'    => 59,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                59  =>
                    [
                        'name'         => 'Saldus',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.666667',
                        'lng'          => '22.5',
                        'county_id'    => 60,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                60  =>
                    [
                        'name'         => 'Limbaži',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.510278',
                        'lng'          => '24.714167',
                        'county_id'    => 61,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                61  =>
                    [
                        'name'         => 'Baltinava',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.943936',
                        'lng'          => '27.644011',
                        'county_id'    => 62,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                62  =>
                    [
                        'name'         => 'Preiļi',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.293981',
                        'lng'          => '26.724786',
                        'county_id'    => 63,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                63  =>
                    [
                        'name'         => 'Aizkraukle',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.602732',
                        'lng'          => '25.263842',
                        'county_id'    => 64,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                64  =>
                    [
                        'name'         => 'Gulbene',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.183333',
                        'lng'          => '26.75',
                        'county_id'    => 65,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                65  =>
                    [
                        'name'         => 'Cibla',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.5498',
                        'lng'          => '27.883699',
                        'county_id'    => 66,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                66  =>
                    [
                        'name'         => 'Rugāji',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.0',
                        'lng'          => '27.133333',
                        'county_id'    => 67,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                67  =>
                    [
                        'name'         => 'Smiltene',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.433333',
                        'lng'          => '25.9',
                        'county_id'    => 68,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                68  =>
                    [
                        'name'         => 'Riebiņi',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.333333',
                        'lng'          => '26.8',
                        'county_id'    => 69,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                69  =>
                    [
                        'name'         => 'Aizpute',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.716667',
                        'lng'          => '21.6',
                        'county_id'    => 70,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                70  =>
                    [
                        'name'         => 'Tukums',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.966944',
                        'lng'          => '23.155278',
                        'county_id'    => 71,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                71  =>
                    [
                        'name'         => 'Baldone',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.742778',
                        'lng'          => '24.394444',
                        'county_id'    => 72,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                72  =>
                    [
                        'name'         => 'Viesīte',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.35',
                        'lng'          => '25.55',
                        'county_id'    => 73,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                73  =>
                    [
                        'name'         => 'Garkalne',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.044859',
                        'lng'          => '24.419507',
                        'county_id'    => 74,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                74  =>
                    [
                        'name'         => 'Lieģi',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.583333',
                        'lng'          => '21.333333',
                        'county_id'    => 75,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                75  =>
                    [
                        'name'         => 'Balvi',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.133333',
                        'lng'          => '27.25',
                        'county_id'    => 76,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                76  =>
                    [
                        'name'         => 'Madona',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.85',
                        'lng'          => '26.216667',
                        'county_id'    => 77,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                77  =>
                    [
                        'name'         => 'Zilupe',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.386007',
                        'lng'          => '28.121781',
                        'county_id'    => 78,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                78  =>
                    [
                        'name'         => 'Kuldīga',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.968986',
                        'lng'          => '21.968037',
                        'county_id'    => 79,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                79  =>
                    [
                        'name'         => 'Strenči',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.625688',
                        'lng'          => '25.68185',
                        'county_id'    => 80,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                80  =>
                    [
                        'name'         => 'Sala',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.516667',
                        'lng'          => '25.766667',
                        'county_id'    => 81,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                81  =>
                    [
                        'name'         => 'Olaine',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.785278',
                        'lng'          => '23.938056',
                        'county_id'    => 82,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                82  =>
                    [
                        'name'         => 'Aknīste',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.166667',
                        'lng'          => '25.75',
                        'county_id'    => 83,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                83  =>
                    [
                        'name'         => 'Nīca',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.35',
                        'lng'          => '21.066667',
                        'county_id'    => 84,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                84  =>
                    [
                        'name'         => 'Jēkabpils',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.483333',
                        'lng'          => '25.85',
                        'county_id'    => 85,
                        'region_id'    => 1,
                        'type'         => 'city',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                85  =>
                    [
                        'name'         => 'Auce',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.466667',
                        'lng'          => '22.883333',
                        'county_id'    => 86,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                86  =>
                    [
                        'name'         => 'Viļaka',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.184299',
                        'lng'          => '27.671861',
                        'county_id'    => 87,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                87  =>
                    [
                        'name'         => 'Vaiņode',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.433333',
                        'lng'          => '21.866667',
                        'county_id'    => 88,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                88  =>
                    [
                        'name'         => 'Mālpils',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.011111',
                        'lng'          => '24.963056',
                        'county_id'    => 89,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                89  =>
                    [
                        'name'         => 'Ogre',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.816667',
                        'lng'          => '24.6',
                        'county_id'    => 90,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                90  =>
                    [
                        'name'         => 'Ilūkste',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '55.977854',
                        'lng'          => '26.297769',
                        'county_id'    => 91,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                91  =>
                    [
                        'name'         => 'Kandava',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.038944',
                        'lng'          => '22.772354',
                        'county_id'    => 92,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                92  =>
                    [
                        'name'         => 'Ozolnieki',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.686389',
                        'lng'          => '23.787778',
                        'county_id'    => 93,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                93  =>
                    [
                        'name'         => 'Carnikava',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.129346',
                        'lng'          => '24.284233',
                        'county_id'    => 94,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                94  =>
                    [
                        'name'         => 'Krāslava',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '55.896882',
                        'lng'          => '27.171999',
                        'county_id'    => 95,
                        'region_id'    => 4,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                95  =>
                    [
                        'name'         => 'Valmiera',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.55',
                        'lng'          => '25.4',
                        'county_id'    => 96,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                96  =>
                    [
                        'name'         => 'Ādaži',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.07045',
                        'lng'          => '24.337126',
                        'county_id'    => 97,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                97  =>
                    [
                        'name'         => 'Naukšēni',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.883333',
                        'lng'          => '25.45',
                        'county_id'    => 98,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                98  =>
                    [
                        'name'         => 'Pilsrundāle',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.416667',
                        'lng'          => '24.0',
                        'county_id'    => 99,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                99  =>
                    [
                        'name'         => 'Dobele',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.625',
                        'lng'          => '23.278611',
                        'county_id'    => 100,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                100 =>
                    [
                        'name'         => 'Ape',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.533333',
                        'lng'          => '26.666667',
                        'county_id'    => 101,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                101 =>
                    [
                        'name'         => 'Salaspils',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.861111',
                        'lng'          => '24.349444',
                        'county_id'    => 102,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                102 =>
                    [
                        'name'         => 'Ropaži',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.973889',
                        'lng'          => '24.633611',
                        'county_id'    => 103,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                103 =>
                    [
                        'name'         => 'Brocēni',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.7',
                        'lng'          => '22.533333',
                        'county_id'    => 104,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                104 =>
                    [
                        'name'         => 'Skrīveri',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.65',
                        'lng'          => '25.133333',
                        'county_id'    => 105,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                105 =>
                    [
                        'name'         => 'Skrunda',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.683333',
                        'lng'          => '22.016667',
                        'county_id'    => 106,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                106 =>
                    [
                        'name'         => 'Priekule',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.433333',
                        'lng'          => '21.583333',
                        'county_id'    => 107,
                        'region_id'    => 3,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                107 =>
                    [
                        'name'         => 'Saulkrasti',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.259894',
                        'lng'          => '24.418873',
                        'county_id'    => 108,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                108 =>
                    [
                        'name'         => 'Līgatne',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '57.233333',
                        'lng'          => '25.05',
                        'county_id'    => 109,
                        'region_id'    => 2,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                109 =>
                    [
                        'name'         => 'Pļaviņas',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.616667',
                        'lng'          => '25.716667',
                        'county_id'    => 110,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                110 =>
                    [
                        'name'         => 'Nereta',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.204428',
                        'lng'          => '25.307656',
                        'county_id'    => 111,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                111 =>
                    [
                        'name'         => 'Vecumnieki',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.606389',
                        'lng'          => '24.522222',
                        'county_id'    => 112,
                        'region_id'    => 1,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
                112 =>
                    [
                        'name'         => 'Piņķi',
                        'country_code' => 'LVA',
                        'population'   => 0,
                        'capital'      => false,
                        'area_size'    => '0.00',
                        'lat'          => '56.941891',
                        'lng'          => '23.913654',
                        'county_id'    => 113,
                        'region_id'    => 5,
                        'type'         => 'town',
                        'created_at'   => Carbon::now(),
                        'updated_at'   => Carbon::now(),
                    ],
            ]
        );

    }
}
